######################################################################
# Automatically generated by qmake (3.0) Thu Jun 25 11:00:56 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = cppxslt
INCLUDEPATH += .
QMAKE_CXXFLAGS = -std=c++11

# Input
HEADERS += XmlWriter.h \
    LiteralXml.h
SOURCES += bra.cpp main.cpp testserializer.cpp
